#ifndef GPIO_DBUG_H_
#define GPIO_DBUG_H_
void
gpio_dbug_init(void);
void gpio_toggle(uint8_t gpio_indx);
#define DEBUG_GPIO_NOT_AVAILABLE	0xff
#define DEBUG_ADV_FLOW 0
#define DEBUG_TIMING 1
#if DEBUG_ADV_FLOW
#define DEBUG_ADV_TXCB_GPIO     0
#define DEBUG_ADV_TXDONECB_GPIO     1
#define DEBUG_ADV_WFRTIMEOUT_GPIO   2
#define DEBUG_ADV_DONECB_GPIO       3
#else
#define DEBUG_ADV_TXCB_GPIO     	DEBUG_GPIO_NOT_AVAILABLE
#define DEBUG_ADV_TXDONECB_GPIO     DEBUG_GPIO_NOT_AVAILABLE
#define DEBUG_ADV_WFRTIMEOUT_GPIO   DEBUG_GPIO_NOT_AVAILABLE
#define DEBUG_ADV_DONECB_GPIO       DEBUG_GPIO_NOT_AVAILABLE
#endif

#if DEBUG_TIMING

#define SCHEDULE_START     DEBUG_GPIO_NOT_AVAILABLE
#define TMR0_COMPARE2		0
#define TMR0_COMPARE0		1
#define TMR0_TICK			2
#define TMR0_OVERFLOW		3
#define OS_TICK		 4
#define OS_IDLE_TASK_GPIO	5
#define PHY_ISR			6



#define TX_START_TIME_SET DEBUG_GPIO_NOT_AVAILABLE
#define RX_START_TIME_SET DEBUG_GPIO_NOT_AVAILABLE
#define RX_START     DEBUG_GPIO_NOT_AVAILABLE

#define WFR_TIMEOUT   DEBUG_GPIO_NOT_AVAILABLE
#define TX_END       DEBUG_GPIO_NOT_AVAILABLE
#define RX_END       DEBUG_GPIO_NOT_AVAILABLE//6
#define TMR_INTERRUPT	DEBUG_GPIO_NOT_AVAILABLE//7
#define TMR0_INTERRUPT	DEBUG_GPIO_NOT_AVAILABLE
#else
#define SCHEDULE_START     	DEBUG_GPIO_NOT_AVAILABLE
#define TX_START_TIME_SET 	DEBUG_GPIO_NOT_AVAILABLE
#define RX_START_TIME_SET 	DEBUG_GPIO_NOT_AVAILABLE
#define RX_START     		DEBUG_GPIO_NOT_AVAILABLE

#define WFR_TIMEOUT   		DEBUG_GPIO_NOT_AVAILABLE
#define TX_END       		DEBUG_GPIO_NOT_AVAILABLE
#define RX_END       		DEBUG_GPIO_NOT_AVAILABLE
#endif



#endif